### ISSUE TITLE
Support for multiple PHP versions

### ISSUE THREAD

**Issue by FireDrunk** [brianium/paratest#227] opened 2017-02-13 09:17 UTC
It would be nice to have support for multiple PHP Versions at the same time. We are in the transition from PHP 5.6 (default on systems) to PHP7.1 (/usr/bin/php71).

We can overrule the PHPunit binary, but we can't tell paratest to start PHPunit with PHP7.1 (using /usr/bin/php71).

Is it possible to add this as a feature?

**Comment by gabrielpreston** [comment] 2017-02-13 16:38
Does the `--phpunit` flag not work as expected for you?

**Comment by gabrielpreston** [comment] 2017-02-13 16:39
Deleted my previous comment, sorry. I misread your post and caught my mistake right after I commented.

**Comment by FireDrunk** [comment] 2017-02-20 09:27
Any update on this?

**Comment by julianseeger** [comment] 2017-02-23 02:04
Well, by changing the phpunit binary, you can change the php binary, too. 
The phpunit file is just an executable script and because it starts with `#!/usr/bin/env php`, it is executed with php. By creating your own phpunit startup-script that uses php71 instead, you are done. Maybe it would even be enough to change the environment while running paratest, but I don't know if the environment is passed to phpunit.

On the other hand ... I would advise you to setup some kind of reproducible environment to run your tests in like a vagrant-vm or a docker-container (just to name a few). Then you could have one php5 and one php7 container and remove the errorproneness of two php versions available.

**Comment by julianseeger** [comment] 2017-02-26 01:24
@FireDrunk you now got two ways to act on your problem. I hope this solves it for you.
As I see no action left for paratest itself, I'll close this issue. Feel free to comment / reopen if you disagree.

**Closed by julianseeger** 2017-02-26 01:24 UTC
Labels: question
