### ISSUE TITLE
Using @group throws exception 

### ISSUE THREAD

**Issue by jameshd** [brianium/paratest#146] opened 2015-02-04 11:41 UTC
Whenever we use the @group annotation we encounter the following exception

```
[RuntimeException]                                                                                                                      
  Log file /tmp/PT_YQNOiy is empty.                                                                                                       
                  This means a PHPUnit process was unable to run /src/test/Components/CompetitionFilter/FilterTest.php  
                  Maybe there is more than one class in this file.
```

Having traced the code in ParaTest we've found where the exception is being thrown and that the Reader->hasResults() method is returning false, thus causing the exception. 

However, should this code even be being executed as the test in the Exception does not contain the requested @group annotation?

With the following lines commented out  - the tests work as expected, but there could be underlying issues to which we're not aware. 

``` php

       if (!$reader->hasResults()) {
            throw new \RuntimeException("Log file " . $test->getTempFile() . " is empty.
                This means a PHPUnit process was unable to run " . $test->getPath() . "
                Maybe there is more than one class in this file.");
        }
        $this->results->addReader($reader);
```

Any advice would be appreciated.

**Comment by julianseeger** [comment] 2015-02-04 22:41
Maybe you've hit a bug.

The codeblock that throws this exception is relatively new and the [integration test for the group-filter](https://github.com/brianium/paratest/blob/948105b7e98d1ce14f56139284d369f8237dce13/test/functional/GroupTest.php) seems to not cover this scenario where a whole file has no matching group attribute.
This can be confirmed easily by extending the fixture for the [GroupTest](https://github.com/brianium/paratest/blob/948105b7e98d1ce14f56139284d369f8237dce13/test/functional/GroupTest.php) with a second file that contains no matching groups. In your case, this should then lead to this exception.

**Comment by gabrielpreston** [comment] 2015-05-12 20:48
I run into the same issue when I tried upgrading from phpunit 3.7 to 4.0. It seems that starting with v4, the log file is written differently. In 3.7, the log file included information about the test and said there were zero tests run, whereas in 4.0, the log file terminates with <testsuites/> and includes no more information.

**Comment by gabrielpreston** [comment] 2015-05-12 21:53
This is how the junit log file looks now when using phpunit 4 and you pass a @group that doesn't match a test that gets passed from paratest to phpunit.
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>
```

**Comment by fiddur** [comment] 2015-05-13 13:16
I have the same issue with --exclude-group

**Comment by matteomoretti** [comment] 2015-05-17 09:10
Running paratest from dev-master with phpunit 4.6.6 the bug exists. It disappears if you comment out 
```php
if (!$reader->hasResults()) { .... }
```

**Comment by julianseeger** [comment] 2015-05-21 19:45
Is the behavior of release 0.12.1 better?

**Comment by gabrielpreston** [comment] 2015-05-21 19:56
Unfortunately no. The error still occurs, just with a little less information in the exception being thrown.

**Comment by gabrielpreston** [comment] 2015-05-22 00:46
Here are the two scenarios in which I've seen the failure condition come up:

A @group provided, and a test belongs to no groups.
A @group provided, and an exclude-@group is provided, and a test belongs to both groups.

And to reiterate what seems to be happening, at least in my situations, is that based on what paratest passes to phpunit, if phpunit decides a test is not going to be run, the resulting JUnit log file that gets written does not contain the appropriate XML nodes that paratest was expecting to be there. This behavior started happening in version 4 of phpunit.

**Comment by jaredmcateer** [comment] 2015-07-15 13:25
I've written how to reproduce this issue with some minimal test cases in #164

**Comment by Djamiyo** [comment] 2015-09-14 15:06
I faced the same problem. Any thoughts how it can be fixed?

**Comment by PieterDC** [comment] 2015-10-22 14:11
I faced the same problem.

**Comment by jeffminard-ck** [comment] 2015-11-04 19:19
Here is a very clear example of the problem: https://github.com/jeffminard-ck/paratest-error

I've ended up patching the system to not throw and error in this situation and also had to modify another place in the code to not fail when iterating over the empty test suite (which it assumes will have elements)

**Comment by jeffminard-ck** [comment] 2015-11-04 19:29
Ah, @jaredmcateer provided a better example I see.

**Comment by jeffminard-ck** [comment] 2015-11-04 21:25
I've tossed in some work on the unit tests to show where these deficiencies lie:

https://github.com/brianium/paratest/compare/master...jeffminard-ck:exclude-include-groups?expand=1

I also updated the code to allow those tests to pass as expected. I don't think I'm handling "no test run" properly (I imagine it has a non-zero exit code, but haven't checked yet). I also haven't done comprehensive tests on a test file that has a mix of groups with more multiple methods and how that should play out.

**Comment by carlo1138** [comment] 2016-02-23 23:03
We had to fork and patch the project to use class level `@group` annotations. This worked for us, but I don't think it's good or general enough for a PR
```diff
diff --git a/src/ParaTest/Runners/PHPUnit/SuiteLoader.php b/src/ParaTest/Runners/PHPUnit/SuiteLoader.php
index 86c22f8..68c7f3c 100644
--- a/src/ParaTest/Runners/PHPUnit/SuiteLoader.php
+++ b/src/ParaTest/Runners/PHPUnit/SuiteLoader.php
@@ -109,10 +109,18 @@ class SuiteLoader
      */
     private function initSuites()
     {
-        foreach ($this->files as $path) {
+        foreach ($this->files as $i => $path) {
             try {
                 $parser = new Parser($path);
                 if ($class = $parser->getClass()) {
+                    if ($this->options->groups) {
+                        $classGroups = $this->methodGroups($class);
+                        if (!$this->testMatchGroupOptions($classGroups)) {
+                            unset($this->files[$i]);
+
+                            continue;
+                        }
+                    }
                     $this->loadedSuites[$path] = $this->createSuite($path, $class);
                 }
             } catch (NoClassInFileException $e) {
```

**Comment by julianseeger** [comment] 2016-06-09 20:04
We may have a fix (now with a green build) for this and #164 in https://github.com/brianium/paratest/pull/201
Can somebody confirm the fix? If so, a little test and we could get it in.

**Comment by julianseeger** [comment] 2017-02-23 23:42
Can anyone please confirm that this issue is fixed in the current master?

**Comment by lemartin** [comment] 2017-05-13 12:45
Just stumbled across this issue in `0.14.0`. It does not occur in `dev-master`.

**Comment by julianseeger** [comment] 2017-05-13 13:38
thx

**Closed by julianseeger** 2017-05-13 13:38 UTC
Labels: bug, unconfirmed

**Comment by julianseeger** [comment] 2017-05-13 13:49
FTR: Contained in 0.14.1 (that now exists)
